name: wddesignstudio
description: Strona WD Design Studio (Flutter Web)
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  flutter_localizations: { sdk: flutter }
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.9.1

  # (opcjonalnie na później) file_picker / go_router / provider
  # file_picker: ^8.0.0
  # go_router: ^14.0.0
  # provider: ^6.1.2

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hero.jpg
    - assets/images/mini_proj1.jpg
    - assets/images/proj1_1.jpg
    - assets/images/proj1_2.jpg   
    - assets/images/proj1_3.jpg
    - assets/images/proj1_4.jpg
    - assets/images/proj1_5.jpg
    - assets/images/proj1_6.jpg
    - assets/images/mini_proj2.jpg
    - assets/images/proj2_1.jpg
    - assets/images/proj2_2.jpg
    - assets/images/proj2_3.jpg
    - assets/images/weronika.jpg
    - assets/images/mini_proj3.jpg
    - assets/images/mini_proj4.jpg
    - assets/images/proj3_1.jpg
    - assets/images/proj3_2.jpg
    - assets/images/proj3_3.jpg
    - assets/images/proj4_1.jpg
    - assets/images/proj4_2.jpg
    - assets/images/proj4_3.jpg
    - assets/images/proj4_4.jpg
    - assets/images/proj4_5.jpg
    - assets/images/proj4_6.jpg
    - assets/images/proj4_7.jpg
    - assets/images/mini_proj5.jpg
    - assets/images/proj5_1.jpg
    - assets/images/mini_proj6.jpg
    - assets/images/proj6_1.jpg
    - assets/images/mini_proj7.jpg
    - assets/images/proj7_1.jpg
    - assets/images/proj7_2.jpg
    - assets/images/mini_proj8.jpg
    - assets/images/proj8_1.jpg
    - assets/images/mini_proj9.jpg
    - assets/images/proj9_1.jpg
    - assets/images/proj9_2.jpg
    - assets/images/mini_proj10.jpg
    - assets/images/proj10_1.jpg
    - assets/images/mini_proj11.jpg
    - assets/images/proj11_1.jpg
    - assets/images/mini_proj12.jpg
    - assets/images/proj12_1.jpg
    - assets/images/proj12_2.jpg
    - assets/images/proj12_3.jpg